/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside'];
    ElButton: typeof import('element-plus/es')['ElButton'];
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider'];
    ElContainer: typeof import('element-plus/es')['ElContainer'];
    ElMenu: typeof import('element-plus/es')['ElMenu'];
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem'];
    Home: typeof import('./views/home/index.vue')['default'];
    IEpBell: typeof import('~icons/ep/bell')['default'];
    IEpDocument: typeof import('~icons/ep/document')['default'];
    IEpExpand: typeof import('~icons/ep/expand')['default'];
    IEpFiles: typeof import('~icons/ep/files')['default'];
    IEpList: typeof import('~icons/ep/list')['default'];
    IEpUser: typeof import('~icons/ep/user')['default'];
    Index: typeof import('./views/index/index.vue')['default'];
    Layout: typeof import('./components/Layout/index.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
  }
}
